# Урок 5

In [10]:
import numpy as np

# Сингулярное разложение матриц

## Практическое задание

1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$


2. Для матрицы из предыдущего задания найти с помощью NumPy и вручную:

    а) евклидову норму;
    
    б) норму Фробениуса.

__Решение__
__1.__

In [2]:
A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [3]:
U, s, W = np.linalg.svd(A)

# Транспонируем матрицу W
V = W.T

# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
Sigma = np.zeros_like(A, dtype=float)
Sigma[np.diag_indices(min(A.shape))] = s

In [4]:
print(f'Матрица U:\n{U}')
print(f'Матрица Sigma:\n{Sigma}')
print(f'Матрица V:\n{V}')

Матрица U:
[[ 0.17056501  0.15680918 -0.53077508 -0.79905375 -0.16158397]
 [ 0.39287016 -0.52933945  0.6134793  -0.43375771  0.03082495]
 [-0.14366152 -0.82449256 -0.52379105  0.14049848  0.07400343]
 [ 0.88843702  0.06074346 -0.24655277  0.37755832 -0.06042632]
 [ 0.08125046  0.10831843 -0.08231425 -0.10524851  0.98173958]]
Матрица Sigma:
[[8.82486885 0.         0.        ]
 [0.         6.14060608 0.        ]
 [0.         0.         2.53271528]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
Матрица V:
[[ 0.07116451 -0.36737824 -0.92734505]
 [ 0.71702467  0.66514082 -0.20847855]
 [ 0.69340553 -0.65009301  0.31075368]]


### Норма Евклидову 

In [11]:
s[0]

8.824868854820448

In [12]:
np.linalg.norm(A, ord=2)

8.824868854820442

### Норма Фробениуса

In [14]:
np.sqrt(np.sum(A**2))

11.045361017187261

In [16]:
np.sqrt(np.sum(s**2))

11.045361017187265

In [8]:
np.linalg.norm(A, ord=None)

11.045361017187261

In [9]:
np.linalg.norm(A)

11.045361017187261

In [ ]:
np.linalg.norm(A, ord='fro')

11.045361017187261